# Generated by Django 5.0.8 on 2024-09-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('Codigo_Producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre_Producto', models.CharField(max_length=150)),
                ('Marca', models.CharField(max_length=150)),
                ('Precio_Unitario', models.DecimalField(decimal_places=3, max_digits=20)),
                ('ID_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Categorias.categorias')),
            ],
        ),
    ]
