# Generated by Django 5.0.8 on 2024-09-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Precio_Unitario',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
