# Generated by Django 5.0.8 on 2024-09-20 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_alter_productos_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='Imagen_Producto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
