# Generated by Django 5.0.8 on 2024-09-20 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_productos_imagen_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productos',
            name='Imagen_Producto',
        ),
    ]
