# Generated by Django 5.0.8 on 2024-09-12 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProductos',
            fields=[
                ('Codigo_Venta_Producto', models.BigAutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.CharField(max_length=150)),
                ('Precio_Unitario', models.CharField(max_length=150)),
                ('Codigo_Factura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Categorias.categorias')),
                ('Codigo_Producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Productos.productos')),
            ],
        ),
    ]
