# Generated by Django 5.0.8 on 2024-09-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaProductos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproductos',
            name='Codigo_Factura',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ventaproductos',
            name='Precio_Unitario',
            field=models.IntegerField(),
        ),
    ]
