# Generated by Django 5.0.8 on 2024-09-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VentaProductos', '0002_alter_ventaproductos_codigo_factura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventaproductos',
            name='Cantidad',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ventaproductos',
            name='Precio_Unitario',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
