# Generated by Django 5.0.8 on 2024-09-19 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VentaProductos', '0003_alter_ventaproductos_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ventaproductos',
            old_name='Precio_Unitario',
            new_name='Precio',
        ),
    ]
