# Generated by Django 5.0.8 on 2024-09-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('ID_Categoria', models.BigAutoField(primary_key=True, serialize=False)),
                ('Nombre_Categoria', models.CharField(max_length=150)),
            ],
        ),
    ]
